name: yonkers deployment

on:
  push:
    branches:
      - yonkers

jobs:
  deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    environment: yonkers    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: imagick, swoole

      - name: Install Packages
        run: composer install --no-dev

      - name: scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_CERT }}
          scp: |
            ./* => ./api_yonkersgarage/
